GROQ_API_KEY= "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"

[aws]
access_key = "AKIA5FTZCHTOM4Q7JFXS"
secret_key = "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"
bucket_name = "document-upload2"
region = "ap-south-1" 
